eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: "http://eureka-service-0.eureka-svc.cloud-demo.svc.cluster.local:8081/eureka,\
      http://eureka-service-1.eureka-svc.cloud-demo.svc.cluster.local:8081/eureka,\
      http://eureka-service-2.eureka-svc.cloud-demo.svc.cluster.local:8081/eureka"
    fetch-registry: true
    register-with-eureka: true